spring:
  #RabbitMq
  rabbitmq:
    host: # 你的虚拟机IP
    port: # 端口
    virtual-host: /Learning # 虚拟主机
    username: ZZGEDA_Learning # 用户名
    password:  # 密码

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 
  database: ssm_db
