spring:
  #RabbitMq
  rabbitmq:
    host: # 你的虚拟机IP
    port:  # 端口
    virtual-host: /Learning # 虚拟主机
    username: ZZGEDA_Learning # 用户名
    password: # 密码


mysql:
  host: #生产环境的host
  port: #生产环境的port
  username: root
  password: #myal密码
  database: ssm_db
