server:
  port: 18081
rabbitmq:
  host: 172.19.38.4 # 你的虚拟机IP
  port: 34746 # 端口
  virtual-host: /Learning # 虚拟主机
  username: ZZGEDA_Learning # 用户名
  password: # 密码


mysql:
  host: 172.19.38.4 #生产环境的host
  port: 33170 #生产环境的port
  username: root
  password: zZ-szshyjbz16D #myal密码
  database: ssm_db


jedis:
  host: 8.130.99.124
  port: 36689
  password: zZ-szshyjbz16D
  database: 0    #redis数据库的索引号
  maxIdle: 100  #连接池最大空闲数
  minIdle: 0  #连接池最小空闲数
  maxTotal: 100   #连接池最大连接数
  maxWaitMillis: 500  #这是当连接池耗尽时，调用者最大等待时间为500毫秒
  testOnBorrow: false   #这是从连接池获取连接时，是否进行有效性检查设置为false
  testOnReturn: true  #这是向连接池返回连接时，是否进行有效性检查设置为true。
